---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-operator
  namespace: gotk-system
spec:
  path: ./manifests/charts/istio-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: istio
  interval: 10m0s
