---
apiVersion: kustomize.toolkit.fluxcd.io/v2beta1
kind: Kustomization
metadata:
  name: istio-operator
  namespace: gotk-system
spec:
  chart:
    spec:
      chart: ./manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
  interval: 10m0s
