---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: meme-detector
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./meme-detector/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

