apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative-operator
  namespace: flux-system
spec:
  interval: 30m
  path: ./knative
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system