apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: argo
spec:
  encryptedData:
    accessKey: AgAvzuUAd+W94c/LQ9eJ4CYfVE3PQsvJZPNBDdLX5gO55VLKAWK2HSU30NQcYUWkN1CYrVoi/c6d78qHM+ln//4oeOv6KIaFCmxp7fxxa/t+KPiWUfbZf9LWdLeJaBklDar+PEGyHzIYWpApr6r2mOdxXfHQNils8t6c1tz3j0W4Aqbeo4EWDoZuYugvYfnVYtrfXth5QKLOusNITwPa4hX4KhGBDrH+FCJAVWU2REM3yGNQxzof9hhdRy/QGQpZ/Va0DBlVWVDP6wi2Molnry/3+my1HTjpqCFzM1Dqbi8VhW5Uniz0GvNuAGTl8xN42hfchU3nnrSJxUvoASB5PD9zOQSETgbZuSjfaCrY+eQJbXjgufbX7URP0DypYi87W7p17CW1IDkA45kWKJG3O7V6AfJ2AP1zmoMcpazsK3MOVhwYdocu8hczKRjt2I19K1DzP93+eNqoADBU7iQkWNaa8Bvba8KL2aXeRLFZvgliq61WNX5dc7Hw2P7LQEiZdxJhTz/x+63VEahinlMlYsOW4COZkkwk1FLUCQwgYUFn7SUU53ooR0F8SJ95upUP0Vi2yN/xEh2isCs+9q2WqCL+uX4a/+YbSospgI46gQTRvKw2ziB4VdFwjBTu7qBMqb14Ww2miq/dZFv8OGg1zXGKFVQ/wFMAHaQzq82ganuFvxg5o/VQtJ+JvlWWJzMBgnDP8jGgEBW2koLQTg==
    secretKey: AgCvkga8U1DeL6xo7dD2jmTr/EVoJ+fjAmx7U0lNYF1Kb59PM/h5Q8aarBd/DW5EiMgD/ZGbI7O8zxz3yGx/zmIcW3WlNA9dmm57whM5iDnasylnj5wdFLylt3mWHM2YsSC8e8NVou/UpoUwM8n643jVxdT0dHxtrVwypRh5GwNiScQnl6S9/tRi319qAzXeoFlfZO0gaK/OMdAeJM/akg+4JNpQtmsjKMcX5Y+Q6RjlYeFGMWqR892cnUJZHLjjZKBANqzpvrMz9OWbdbvlR7JYnO3t0KLGloXOwWnYrZ2NhIKkGL6afCta9wrv66N9H6ETWkO/FBDrLNXfPt1jQqQZgnmclhzFqtst9c33sX8Tmi7NgzDsLCpGwVc2zdhgrwoy60m+MWrcU4xzrreNkuhbS/H+M1BK6LdWjfN9/q7q6vescgWdKhb6z0scisJrLqjGaOepwqSonDS3MQi4Y8a7Buj7Nrika2WZILJn+/+x6lU0KLG0i3QtE7aqUlppQIuMJoX4XTUZikvbsJCw71Fq59nC0XqjSV72ycDCJXCZ3YiiZAxLcka+QIsZMX8Xl1iIVeOung9LKywFxTwldXYj2vQFI3Ze7ufp5rKMk2kGK4RBKmN6tbsuQNECFIp3WFLUNhTIYK7MOsCfTqWpY93PIp8YajZvCP8dkV8rRTlJLif893bFKGAO1+xBF6QXt3wc7zbuFg9MRVw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: argo
    type: Opaque

