apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: argo
spec:
  encryptedData:
    accessKey: AgBC6j5s//dEkpM3Udzdnc/nsd7BKUvW+J3/0a86A6CbzitoZyFQtV4qylalpt5wCtztpsXWiTttTY2R1Plhlb3hweZ+2IuDE1cFW0AxsnxLl+m+4TStRLMWW/VirSflOtKe8+oBUpZloBmCAl4w0o/8yFaHSYPFboulNKpUxiWUVcaIvsBcCsaeIaDJysENKmLXa2PHAQ8XSvT5UYVm5kEnToFWuLcjLxFlMpOiaRp7maLnhk9LCtAI2f0WPHYSEBuoEHTqepUEaK3ZJr3d4U/3Jyov+m+GVKbdA/orMlICDnjyPBaDXmTSGcbYOs6y8p1hR55OomUAU/SqGAnN7PO0UgD7WtL3GrgOs+GbNfOR1eWlP0dgYrWEP4NDfbs1EaAE8sNSm/vBcgs7bMQjP+xicY3veg4tfv6K2mrsxkNRDHFpiMHXJAT4TA0R2+ctllCKuZBJhS+TW4R1x5AKRJ8aSbjMiv3K7fV3uvU8L3MoF6IW/wWBBvrQO2dqq/uqzZsAgELPWQ4qsJ0zc86oIsJns8aDxiicdAXBYtA2FBUtZIZdR+RouYIMpilapIqXTnGZ9YSftyYf2kGgGO+dAR7K0bu7rjBYJfPo+d5WYZsmQB5AlhrLHm6AV4iQ1IJPfPDNuuBmhvEpLkxbzc9YdM2dqBbvRjazvu7xQ0osmQ+LFJnXL9q5+FaFDpg4/HaJmtldJnc+zjRZdFW/QA==
    secretKey: AgCACEDz3fimah8mrCshY+xQBS8pkAZAFPFoa8AAx6OUQs638NCyqleCXOLBJ/EE+2eJM7Bakrc5jx1jLdC9DnvlFlnsbs3BB4HH1wldxADy5Hh3hPGgnKZvrk9Cgb8mRC3uVys5ZpL/t5qnKMEiZNeAi0CBOhFyljf7zD8zEHyRM2nPAeZBALcm1i9XoyahvDzLVflOfYmj758d2sfV9Wx1IWG4zLJ1WPBsQbrNkIt04/bPMVkIEmbeOkzBPmtWCKesO/pfk4IyASd3bKLr8Q3mei8BMpMJMgY/6a2sDN++dV8amYr7nYIVoqi1RHzKRIstNHsL0iMF0EIq1gjpJB29geVs/OG0+jMum9T0rL5doqWF0RD6lvwpfuT/3qyBB3iIsMLj6Omh4Os4zYZdE1ftbEZZ+VlZkRqN33OITwDIb4nPcioH1GyohJDLtmdOo07UVMkdAduCmCtVkA1I3l7p5MsDN2jHTMUDHHIOw5pe33+0Tn5Me1ZhdYkV1juj0zk7bPiHtd+FPfcD5+t2II5ZCtoLwrhRR0K6D/eP6NwVeJPqSb+mhazJ1XJQ9xprq6KnmYV+NSz6+YxKenqfiQHwrgAFaZ+9Z5pvWqlkLU5qKJwnHCjJ0RsmiZ1en631kHq+vzf4f+EyjVvbnU7O+2vFIlds+VqSbZQ/va241tJJuQ9ILi8fgP7KyE6ieKX5/BnafYZ8vBsrYyA=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: argo
    type: Opaque

