apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: argo
spec:
  encryptedData:
    accessKey: AgB+ICbJQdEv0+sQh9VRipX6bX0uJ7y5UomDbjct9NMBUQGk9wldYr8NYgyeeQKxAfspPFpF01trhiQMlPLz2fQ6g5ZxR+iMn1XaVnfJkaCrFj0kTxA7wbR5d2mBuXpA9IwYq+f9xbH7TjCM57oCznKVQ9joAmtEyuitsBdvT7h7vhZSUJ2E1daiU5vkMf8AL+LZy7tq9LzjpS9l0W+SZDr+aARmj5XXk3n8TJ1hPNPNiFbHHUtrSE8pNe2nYKqcqL+R9x5QbLErMCRx9WpleCkNzx0Srl5l8pLu3hqeFBY2te8+KH67qlnMOzz/8hwCdNhLb5nJ8GaUaxEMoA2LZ55wQQQJ5DuLBxNCQzhDq3aqomN7jbvZeBaMV3e8ME+dvA3qVWLohLR/6uE1aVglFb/7vPXZNkOewfsF3ZhOTWZWx8Rk04EJKCeXEy3jiOv3DzLFqukmAI2M0BQqyltu6wzhnYcsNxwsgg29X9cQzbKLjlhE3GuS2NvszyfqqZZG2dMMS+6ZMN+3MHMUuRnnUOOQtzl8uCZAqEzpiZx7p2iOROKKuJAO7GkKHC2iwTjHdAOIxyFEvt3S1utD4Vx+CTK0bdAevPNRri3mw/ufB7Y4ctR9muDIFApWWO8DQ7ynhFWmOJmE3y110cs6EegfUXFCzQ95qO/nCaeHbETjLt/E0FSOaG0ikQaecWaIXsbkoojNCJpNfJ+DMt+jIQ==
    secretKey: AgClZXAEqFMH3tQsHgM8Csl6wTD9eSVFgDXB5nAUsiXozkWltfYoJ+SwpOouc+UNOkqrO8gMgRJ5w7OjPWzlDcE9eCclv+g+N7oIyBSf5kru1KFnFoyTQND0n8jiiziaV72NdnmqQUnw11ang3INZCKqg2rhfst9bBaUpva294ZeJC00wcvzOu/3iPUuvmniAXNXyBrESjIVIzJDLBXPnaLz3U/yhM1KR9ecqFd8JiLhnwCLkOOX9goVEe5rQ9Qlamdt/NPufhTowFcEbDA5iDIGH0R+dpGqcoqnIFIebLTKTkyAoG+hPVjS950K9v4FgZ2dpgRqFZI0UcDBwRGCv7pQxAY5T8NL9bYcezHeey9sRW/DVgzahwHwKKhW4738NlRqWzWrloUaQpcsiAu+rwr9HDN8xTriWD3ApkAV9/fnFhbut904Vgui9ea4Z81TNn2yxIRDUZtipiSwQprGWyigCJsm+4pM9gPZsgThFMhiCVfG62fq1SQkZZUyULIdverofQs5PtnFnBLUQeo1UmP9kBVg1+TM7MGUA2djM+rLIrNoDGezpI8YEWrWcOEiwKd5k7e01PMoJ6xCrIXkxLnASJZsBBWFkjx8N+Mqxds5gkGehJoVtWpppXTt5E5596jNv2ryeOsQ+fPm5ckqUsZaQcvZCd0Pg7NBygtE17uDC9zZBtX9FXHkrNQX66/1gfcOl11/M6GAA+I=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: argo
    type: Opaque

