apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: argo
spec:
  encryptedData:
    accessKey: AgCqUEtydZpXkFKL6U8usvTh/op32WCVLzk4mzTXBgx3Ck8t+9IiVP0YDWgmKkveE8oJelnPn1ET1hMt1m4agTnUS2IhyIunCBq7cNED2z2BW/Z9IN5SNGCQFLRjbra0YKJM7rFQufyvwkpvjp9OeedzzAwaQYTgYtMljt2Ay033urpXqC77nIYufjUCSQHXBYW/tOFLIYwenRW95ZnVLfpaMOyrY24f8rdKDb4m5cc3DwwcjJtPLmb90DXx0xlhrzjA1Tfk9u+5x5UK7UExq/inDBqJuJX3gidAS8uwhQWnQ6CqrQshucjxYiEpD4nbEg23ZHIqtEfQxbbaQ8qvkxuBUxvzl8kSkj6MVzDAixLUkp04/TrOXg23k6f9I0Naere3SikljHUNhsLRPSPFUpj0cRLOlmAI8VuUYEmGQsJzfH+GXfLdHBlJ/oXRXKTiV8vpmsmhjI+W+SU9Bd6lO/5vUMz+a7q4JnPdmC1FLPvxLWSesNxjhQNvvie3WFp/LRJ2P0b7uoKtZbYWljUQvdKdFSDL4NETCA23k3UiGRpKWp4q5tbLb9eAHOTjpqvNI5V9XDAmVtfvvu3MAU+2jxJJUkctQcY+YkpUdC1lstWBMseER1SeA6i/s5PuqPpDKK1yEN/rRK+BAIcBin9zZnXUrEq0LeSivl8E5f/eL5QFPIihwMqsT3xNVlBdjhtTKQCe3sd/qYRyRCM4Qw==
    secretKey: AgClg8Q/x1h1zuC2nYnysKK+U4tJHSzPPXf1QPuMzh9t6muLQ+11e9S36x73gLuk2rpP8WiPJdumrF7yLy3iAyaiU4PkWh5cxEU/5++heD5ptfkEKFsZrWJRqdwK0oWa1T65T543YbYYS29dwAKa1iqa6HM8HHNkj5A/jULYmbm2xnrB6aarHRffCUDZ+AbiCJqpppTqLn+ve/qCJulgI0d+TjdZzpob6TMrX72apnUDuCNJL0xBYzHAPuFZKeeaX2cn8GPzvoavL+J45+S2ArTEFWN4oMTn9QUJeCQBmu8fafqHcBHOh937CfpqZmv/fLyf3tdlEilGxGZlRLeUH71pymTbUzsaCkzi8E1AbDStfHBCNZs4hZ50JGgLWPwRbE9UETzsOKXvygOcugv5H5kKw2e8T+tHtyB/mqKB6TQpvDP22t/krNhzDAd0M0nIFtwOPfui0vkNnQewhLJQSCmjA1PiMJvuGEpmttAk6hFGY79hiL5mhQsDAV13WmRk5e9v8GAMDkTXvTCeengHtCglc5hctqOZh2UlsEHm2cRKzBuFn1x9oUs879sbXCTwrfGLMtc1BPHs+bhDXXCwkFFQERnj+kwVBa1SEJ7UtMBdI1j9j8wVHgSx7t6nGlKFnVTvi2Nx+s2jMwZDy9fPX2XfnBA9QVaXGrsY3FQ3owb28prtARCUjhjDM4IbypvQS7XVIQbi+Jg+qv4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: argo
    type: Opaque

