apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: argo
spec:
  encryptedData:
    accessKey: AgAT0tIdcMI3P5yzzllEjCnyCeZRAMfiJp6K1wbBfKGsNNbdc6mypEXKho+MKLiu3GhtccdDHuHyYm89nGyTcWyxh0futniltg9SclfOWpwpGoU3f2n5lu1TMwD+Ysf5gusaU33zgi0p+VJCXWA/jvHAJEs0Rcc5ypMHWNSlJLF8FAM0Uav5/DehubJJ06hWi55IeTH6Ka5qA49ySYcmWJoDabi7rS9PwkvL+AhSpc7ZCf2uXXf/Y9LdxUcgudw5CL3NUexxAoofwAgATB75rL6ngwHU0iBuMKBAZcSaxtJ+PN8Lg1O7eF99alE2pBPqI8mYiS8o59/ZLnkabFQ41gFlS3GCTZ6jDI1vncAwJGTkWRIrYdSeroqQigLhOEA5SYQViAomx8YPeFMhgtJwawI4eMBD9N+viKkI459SXFrYTfjghqxpFlRqD0+N40x7Q8SaxSLdOhxaXbKga9SZL/QM59mmKZ9Bk5k/njPcZrsprF4fnoLWDX3dGgBpz5x1jA+hbVqSfQ38EYt9bSb8zissfsdhdlC6nB3/rxooFPCiSikvIPI+XGHq4FuEoSCgGiKUklk8ziiy0kGM15P/9CQOhOwUcVdCaRNnH+/xeEnufICMq1IccMD8TMRGvlfT0mH1aK7aIqL7qcCYElDh8cMNpMCSUNml8JfsW207zq36UCZ8nUoMmP1+lM1iGxwD2vFl98PLAmkuQ+OMWA==
    secretKey: AgACvLOiyqWA8JvCnHY2j0Jj89uxCVw/qDZo9/KbSXYXYSHINOo8e648o8uDsv0MrMDrBSXhttVe9CqtNRJN0Aiha95TQL2N/nCPQ9gFitlHpY+k4S/JdkpMYH2y5qZKeYsObCq5kNNB4e9fz4kEawY6J2O8hYm1uGt2oaAdbMFeMhGT3huQ85ZOP2yGsmutXdJqXdiAUp/BFcPm6wt5ZFlx9+SpevY4FbrVEoUfjBnvj0d9KZ8Cc3t71R3T7iVPq7JaGkZRA7goKibJPJpMHxjRSeBWPOT99f1nvtIqznIT7jHs2oFV8RyUKET466D1pQ3N2UERASZsMnXSLp5pEOY5Ewv4SNi4WHLy/pfIgFth8MqHGnuW/g/eU9bcr11TQh3lMnnnU7KdsDNIeQ1HgQUW1WiOOSAw1nhNcomdpxJxD8TpRBWHhg/eX9qapFUhjKy+658TuioMiSQqS9kKULPRoouO9nhkcBtbX/gSCiofXFtMvOMlliyhVIUuvdZP9iwOwQY1iidl68dr0SAH0ppRc3yYsXTuM30FzbkCWqRdVNoiiNxTDLy5/6W9SXp845V+J8wu81XhZSphjIR3Nye/TiExWNXfojuH4hZcKS2rOBu7PrGZ/OYYGWXiuA+cZRgHTFPNhL3fuHfINUeBK+IQ/ICcV2FWyuntdudKQhKBPqf+iqm755K4MzocbyB4ON4PfWwNbNTZ/Wg=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: argo
    type: Opaque

