apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: flux-system
spec:
  encryptedData:
    accessKey: AgAapxWh9ExUw64KTP0iGBWkJJrbYvLd/hIdism2gLN5zsEeFrLVbn9JLmQ5mYXy6vPhDFkjeEGnR6nZr0d6OsgwvCzUf3bMSByRJX6S1u4zSIw1A1yX7fehzPaw6vJiUQh9SRRYHmWBIcT2c/e2RcSc0qph0ioj3ROD2uSufSwVvZC5wOzZox/vXubCj9C3HFPB+n4QUk9kz8jJHaTUQ1hCGxGb1rhBlvhdjlB7FhQd5Nh6Hu+qRQaUhELmmJIUkkr4x/f+psqhz6oOlZlfhImN0oIqR2Io+HSENsL7Jh7gef4n5JgmWA007lDlMMFRFEjfmDcP0zaO/wq0LEpvQ1xHzZ7g2hRMfTdagGUXK0mC7NAbINze4t/RtCzO3avXMASXxrmZhVe06M8URzqDfzvOp+lD30MuwPzo0rO962rKTfdvOZYK+ralGWiN1/XQQwRuD0EZ7raZ3oBrfKnC2/aE9Qu4f6qpv96/2Ay2+NnfohITIPp3wJzoGpAN2d0Vi9L+6Sz3HPxW0wll/3sfJaQr94Xr7FHL6BWFggb+bpBU1G3cWnTG+EN2LN/wAq8iOcm3DrOUx2dyaCUqaMK+JvRoPir/1hZnfLJfv9JgjUtM99t+cV1i9MtoiCNomWFT/wMuI0vVaiOLW6TvxAbT05X5jn30H8S+Kzmu2nLKVdtYjmoXDbpI3fA11xb8eSaXl7v9jGmPvPc6PmFkfQ==
    secretKey: AgBP8cZXz9iZhpKcVK4/uok/Ae0f12FRYQwFiJtvxrru2qEWcXSjgEC22mAu+703e7LbozelO56aqWtxoh4jowE9hBxDWYVfAIZAHuA8f0LdvVZQz06zxutDtdS0ZOHk7QBno5hGZkd7e+lPfM5LpgbHDzz+Sj/2WVaPp66DljIwKIR/rV0JkIJNVv2nyGtZPefFnGChxprTny5aUbA7BgqqzbvpIf3SiiCxf2StqK8V2JYXw4HW47ZIVMtkoaShGGZ5k58vq7HHOFx6mGNABf7wu5pfNovpzYfOOLZal/hnRIYKoV6b0EzJ3bXYOYZ+Rw+mJHSakEYuO4RqqRLm5seVaMU5G1652TAIIu406plGLShQbDa+jHNdUJOG50fMurLrrWDy1nsjvNt1zRgEp4mcyKgxFNsZuFlIQ6DiXHW5vPQPqg9EAD85WckyNhuWUCJHw6hdypvXUjLLRlj1/v21H4apZ+klkwGxUPdPO6qcRAXpPCADQ6W9VyDjfaZqVlrIGCtUarUj94rVVIB0SQyII8YI0BxANNJEJXJDEI8sA7qhXA+QD14wY6dREooxN/lt8iOdPKiTBo2JdVMCIEdNw1RHuTkpwc2Tnu4OgQC3Q9cnzy/DKBsTe4g86O3ZvXbUwWzYnQ/y4kQqcG7kLUjRqXtkyB2vX9t+shVqCho0+/DFt7EcRvdjowXIAalY6tjje35SxTs18gI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: flux-system
    type: Opaque

