apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: flux-system
spec:
  encryptedData:
    accessKey: AgCalWini/n2Naa9enIAMRU9/45do0CTGXv5firHWZXGOouHIzETTD+8KkJYhx5yVGQ8BwHhy+eySuO+Jhw/AGS9pydNlHcitwcZ+520rnS+sBup/5w42O5XBN88CnxOeQztVnujADBZujdGzaMoHZSGyPk92YBH0ImYNeiLPwYnpgUzlobO+unvbMYXQuCKy+xH9b6xlq45eM0Uof98YQPBaUEhlUnlHPUasJi27piE9A+Zz5MY4EH4VisqgG8JDanboNQLFy745j/TDjDGQ9yKiXT49R5S40EPffCYZvrd9naHD1V5kLu7K/D4JbRoURydytBJt30XZyDqaTqhLpss+cQ6zWzWATxbLsqWGlSQ1QJpiFpk85uUHztN4R61rLuXo3ULkJA8RNySL1Eb48eqQskfRHZVX1IhPps0c3Dh37FT3XBN4GLUWgByOQSxzWkGR10MJ8JShb7ySjcO17ABPFftQ2hrbMQ5aWDKIta6JMYwefy2lXT1PjVNlgc9NqCgFtA7iUsU+2TX5elr1YR2FITWuUQxQtE3kiBrzMUf1kbHqT6aOT816Tx6PbGnGfULpAO1Flsl+uHQJDI0LH5PmEXHaITbZRRyY4uyuKvqzCzVc1sM7M/pKXBEUSGYHr/4VKXd3FRyPoaO/RYK/mwgLYqglVYC4FYsIIMHFeq7HJmJbQ/jqBB0GRMwnpXjLax61FwYzsL5qJ7RkA==
    secretKey: AgCIDxcVgXX98j24xG66UTvNm5txswGU9aTVN6PtkCD7vsZaY+bChP1epZAePkeP2CxZ+UBqn8zA51cnvLq18kBzLDCaBMowErj4OyhT2pVSdwZFOJzTUNq6TV8MUdEBPDO4WsTu/NwcUk5U3jX0ORz6U01MQf+1wL8ed3QmGMUljvXQGy8mC32MNH+YXyCxiGoOo+2HCiZq9vTRbtQNHdW5KkwExMnHblQ6bIFkJsATQAdAhWB/zNhWm2JJeyOocidcUDkkqaRoQnYwBz7pN8gapTvB4mJuVoE8QiJ84i1lOC9CRfqQsKnT5hmJuBQaTeRGwH4tZ5c5oYXqPCo0p78sS1zBHCplt3zcMAH24mRjYIftrHr/2tCNSATuIWEHEwoejtrgdXOCmXLdDz6vTNh3f61aUqQ2Pb2xurQM83Tn2YL0SmNwBVr1ZQ2zKeb8kKahUgysmo9jG5McLfz683ElhPk21rKi7kz/QHcMcu7pYUetynlyj58fwEwfCoa0ZvaF7gowcaBGISMZzryHw16JNtw8t2D56N2bubzM97AT9/pXlztJHUbkhCeoCthDwC6j6hlBLkwXI8zAzkR8OjpO89CKiQk7iM0HKO9GPwcvXqJAiokCh4txiFbfTJycIvN1et4Kv9v82B0MjXcnpKI4Cnl98SWHF0Hy0rxfaNUTCbYBQr9eKKTprtvf3eUQcdXeKtswEgzPUAM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: flux-system
    type: Opaque

