
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meme-detector
  namespace: seldon-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: sasumaki/meme-detector
        imagePullPolicy: IfNotPresent
      