---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: master
  url: https://github.com/minio/charts.git

