---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  chart:
    spec:
      chart: ./minio
      sourceRef:
        kind: GitRepository
        name: minio
  interval: 10m0s
  values:
    buckets:
      - name: models
        policy: public
        purge: false
      - name: argo
        policy: public
        purge: false
  valuesFrom:
  - kind: Secret
    name: minio-secret
    valuesKey: accessKey
    targetPath: accessKey
  - kind: Secret
    name: minio-secret
    valuesKey: secretKey
    targetPath: secretKey
  targetNamespace: minio
  releaseName: minio


