---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: gotk-system
spec:
  chart:
    spec:
      chart: ./minio
      sourceRef:
        kind: GitRepository
        name: minio
  interval: 10m0s
  valuesFrom:
  - kind: Secret
    name: minio-secret
    valuesKey: accessKey
    targetPath: accessKey
  - kind: Secret
    name: minio-secret
    valuesKey: secretKey
    targetPath: secretKey
  targetNamespace: minio
  releaseName: minio


