---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seldon-core-analytics
  namespace: flux-system
spec:
  chart:
    spec:
      chart: seldon-core-analytics
      sourceRef:
        kind: HelmRepository
        name: seldonio
        namespace: flux-system
  interval: 120m0s
  targetNamespace: seldon-system
  releaseName: seldon-core-analytics

