---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seldon-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: seldon-core-operator
      sourceRef:
        kind: HelmRepository
        name: seldonio
        namespace: flux-system
  interval: 120m0s
  values:
    istio:
      enabled: true
    usageMetrics:
      enabled: true
  targetNamespace: seldon-system

