---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./manifests/charts/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: istio
  validation: client


