---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/charts/gateways/istio-ingress
      sourceRef:
        kind: GitRepository
        name: istio
  interval: 60m0s
  targetNamespace: istio-system