---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
  interval: 60m0s
