---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 30s
  ref:
    tag: "1.7.6"
  url: https://github.com/istio/istio

