apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  # - https://storage.googleapis.com/knative-nightly/eventing-kafka/latest/source.yaml
  # - ./kafka-config-map.yaml
  # - ./kafka-channel-config.yaml
  - ./eventing.yaml
  # - https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.19.0/eventing-kafka-controller.yaml
  # - https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.19.0/eventing-kafka-broker.yaml
