
apiVersion: v1
kind: Namespace
metadata:
  labels:
    knative-eventing-injection: enabled
  name: default
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    knative-eventing-injection: enabled
  name: knative-eventing
