apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative-eventing
  namespace: flux-system
spec:
  interval: 5m
  path: ./knative
  prune: true
  validation: client
  dependsOn:
    - name: nats-streaming
  sourceRef:
    kind: GitRepository
    name: flux-system