---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nats-config
  namespace: flux-system
spec:
  interval: 60m0s
  dependsOn:
    - name: nats-streaming
  path: ./nats-eventing
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: knative-eventing

