apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: flux-system
spec:
  encryptedData:
    accessKey: AgAKz/GUeyAENEpNr07ny8xttLcJb3K8LtgYpixJvYLWEhW5KCSHH1OlrxiAJ2AsFKtEn/5xTjBMoTYtxtQuOtz381zlm0wFrSQxkVlQ/61IAGxn7dCy/zoLZcmKFf8Zpvh90YcNOK20gM5pcda406+enm7w45UFJ5VD5LnYih1rzT2LKJzmh2mnkiG/rziNO2GZTL79iR5bxrhIGvjA+JxS0ttXeBnFIpNPy1bomgGo+o2cho1+oS6ThTFvRcFQ/+mZ0BRUgrRzjyzjGTvGKoyt4SR8GyZZsAFggfMN+nPaS7jS6nYzV+o7avtCUiSbMGQUheK+XiWHlrm3QrpC+s94H+3IngpbJhwRHVwE0HJj81hBYVpCaugAUZLDr176K4qXsM//1LlUeqjEuj5CqnGNkHLuJYzEtr/WlKF4IWe20NEzNIP+3rKRBb6gZNREpo1eRZmrqaLZTm+PSHAvRYJPo+9kV9t5AyeVi7dxHNmTXY2ITWkR69loA90pBU03UCDx6QzQBfyaxm1FRacjy3DrjNCGPJqcM0xlGWqFGUDMSD4gBOHks+8EB5vN4gpKBQWudO7k6sMW83LWtuIDxPQEoTSej8ZWc7vSauGlEI8TnmI2h5zEG343x5RBdKcmHGvr3MOI0oyY/lMyvDF3WIHTdR9bxdVCg8P5hdfBH0/5fm2CMne3hloFmJ/meUFopKJGh6dH5jQ7B6MHnw==
    secretKey: AgBarWrOaR/LWsvcuB1XOB/t+m3ZBkzA16WQDzEOuam19b5FdEywLCKAxY3eK9dXvLEPA3OVLO3zo4+H09+/qI/ziRRewBarevBEH12Oc5j5yJ8sIL4VYz0RDnTQwmgPP4D+T4J2s1+d87Ot2XN5BH/uf91THzeMGyvN3yMzFPysDFDRjn67Ot78YzKJ29PQqjLpW7hrngO5tQ0O2gvly3z3XqEH09QxJYtIF6Bc8TQl5vIuVhKELlUU4mlmigNK1VBkwP4WLppvwzFzAOZILZZ/xmCt8gDT1UHZqqsw4p0C0IuPSayfFyzkxOn9bld9awY3eZ92CTH1E0Cw1RZcQOvLAkzB400SFTdaO6m/50gALAG+Vodfzjfs2jTl8FHFI41FT7IgETZOvyVArBYyEOglu8TWAERDdog8wXDjyHbty2jBV7eeSDU9QbO0BksrAOsmyihTYSn5d4OvxPF5vpHp+182ueko6q8kePTNnN+Nj8Ujhe/MitecHpPYbPYhFFplQCOfUxGrb2yt1rNqHj9ClBaPeykfzvWfq6oJ2HjDPt6tlXyeXqYwSCdrTFS6lYLVceS6H1nzDp4PzvicBBdFbQJhP5vtCuGVIU9JSYDBHiaJcTA0Z9aURK0efPt+qvfkcz141d4u9o0dFwyzzC+oFeunjFdLi4Z55m9uPuzsV/UhrSaeBzA3pQIwKcj44cCVbfidYtn/WvU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: flux-system
    type: Opaque

