---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: argo
  namespace: flux-system
spec:
  interval: 1000m0s
  path: ./manifests/namespace-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo
  validation: client
  targetNamespace: argo

