apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-channel
  namespace: knative-eventing
data:
  default-ch-config: |
    clusterDefault:
      apiVersion: messaging.knative.dev/v1
      kind: NatssChannel