apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - https://github.com/knative/operator/releases/download/v0.18.0/operator.yaml
  - ./namespace.yaml
  - ./serving.yaml
  - ./eventing.yaml
  # - ./channel.yaml
  # - ./broker.yaml
  # - ./message-dump.yaml
  # - ./seldon-knative-trigger.yaml
