---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mnist
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: sealed-secrets
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: mnist
  dependsOn: 
    - name: istiod
    - name: istio-operator
    - name: istio-base
  validation: client

