---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mnist
  namespace: gotk-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: mnist
  dependsOn: 
    - name: istiod
  validation: client
  targetNamespace: seldon-system

