apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: seldon-eventing-mnist-trigger2
  namespace: seldon-system
spec:
  broker: default
  filter:
    attributes:
      type: io.seldon.serving.inference.request
  subscriber:
    uri: http://message-dumper.seldon-system.example.com
