apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-default-channel
  namespace: seldon-system
  labels:
    eventing.knative.dev/release: devel
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel