apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-display
spec:
  broker: default
  filter:
    attributes:
      type: seldon.mnist-model.default.response
      source: seldon.mnist-model
  subscriber:
    uri: http://event-display