apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-meme-detect
  namespace: seldon-system

spec:
  broker: default
  filter:
    attributes:
      type: io.seldon.serving.inference.request
  subscriber:
    ref:
      apiVersion: machinelearning.seldon.io/v1
      kind: SeldonDeployment
      name: detector