apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-meme-detect
  namespace: seldon-system

spec:
  broker: default
  filter:
    attributes:
      type: io.seldon.serving.inference.request
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: meme-detector