apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-display-request
  namespace: seldon-system

spec:
  broker: default
  filter:
    attributes:
      type: io.seldon.serving.inference.request
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
# ---
# apiVersion: eventing.knative.dev/v1beta1
# kind: Trigger
# metadata:
#   name: event-display-request
#   namespace: seldon-system

# spec:
#   broker: default
#   filter:
#     attributes:
#       type: seldon.mnist-model.seldon-system.request
#   subscriber:
#     ref:
#       apiVersion: v1
#       kind: Service
#       name: event-display