apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: seldon-eventing-mnist-trigger
  namespace: seldon-system
spec:
  broker: default
  filter:
    attributes:
      type: seldon.mnist-model.seldon-system.request
  subscriber:
    uri: http://message-dumper.seldon-system.example.com
