apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: seldon-eventing-mnist-trigger
  namespace: knative-eventing
spec:
  filter:
    attributes:
      type: seldon.mnist-model.seldon-system.request
  subscriber:
    ref:
      apiVersion: machinelearning.seldon.io/v1
      kind: SeldonDeployment
      name: mnist-model