apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-display
  namespace: seldon-system

spec:
  broker: default
  filter:
    attributes:
      type: seldon.mnist-model.seldon-system.response
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display