apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: event-meme-detector-display
  namespace: seldon-system

spec:
  broker: default
  filter:
    attributes:
      type: io.seldon.serving.inference.response
      source: seldon.detector
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
