apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: seldon-eventing-mnist-trigger
  namespace: knative-eventing
spec:
  broker:
   - name: default
     namespace: seldon-system
  filter:
    attributes:
      type: seldon.mnist-model.seldon-system.request
  subscriber:
    ref:
      apiVersion:  serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
      namespace: knative-eventing