apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: event-display
spec:
  broker: default
  filter:
    attributes:
      type: seldon.mnist-model.default.response
      source: seldon.mnist-model
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display