apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: seldon-eventing-mnist-trigger3
spec:
  broker: default
  subscriber:
   ref:
      apiVersion: v1
      kind: Service
      name: event-display