---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: argo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    tag: stable
  ignore: |
    # we apply our own
    /manifests/base/workflow-controller/workflow-controller-configmap.yaml
  url: https://github.com/argoproj/argo

