---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: argo-events
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./argo-events
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: argo

