name: Release application

on:
  push:

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      run: ls -la
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - 
      name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        path: mnist
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sasumaki/mnist
        tag_with_ref: true
    - 
      name: Get Git Short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${{ github.sha }} | cut -c1-7)"

    - 
      run: cd ./mnist
    - 
      name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    - 
      name: Set image to manifest
      run: |-
        ./kustomize edit set image MODEL_IMAGE="sasumaki/mnist:sha-${{ steps.slug.outputs.sha7 }}"
    - 
      run: cd ..