name: Sekrits
on:
  push:

jobs:
  build-publish:
    name: Rewrite secrets
    runs-on: ubuntu-latest
    steps:
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
          kustomize: 3.5.5
          helm: 2.16.7
          helmv3: 3.2.1
          kubeseal: 0.12.5
          kubeaudit: 0.11.5
          command: |
            echo "Run conftest"
            kustomize build test/kustomize | conftest test -p test/policy -
            echo "Run kubeval"
            helmv3 template ./charts/test | kubeval --strict